[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200

[[redirects]]
  from = "/"
  to = "/protocols/"

[[redirects]]
  from = "/protocols/kde-screencast"
  to = "/protocols/kde-zkde-screencast-unstable-v1"

[[redirects]]
  from = "protocols/linux-dmabuf-unstable-v1"
  to = "protocols/linux-dmabuf-v1"

[[redirects]]
  from = "/protocols/wayland-protocols/*"
  to = "/protocols/wayland-protocols-gitlab.html"
  status = 200
  force = true

[[redirects]]
  from = "/protocols/*"
  to = "/protocols/404.html"
  status = 404
