[build.environment]
NODE_VERSION = "14"

[[redirects]]
from = "/api/event"
status = 200
to = "https://plausible.io/api/event"

[[redirects]]
from = "/"
to = "/protocols/"

[[redirects]]
from = "/protocols/kde-screencast"
to = "/protocols/kde-zkde-screencast-unstable-v1"

[[redirects]]
from = "/protocols/linux-dmabuf-unstable-v1"
to = "/protocols/linux-dmabuf-v1"

[[redirects]]
from = "/protocols/tablet-unstable-v2"
to = "/protocols/tablet-v2"

[[redirects]]
force = true
from = "/protocols/wayland-protocols/*"
status = 200
to = "/protocols/wayland-protocols-gitlab.html"

[[redirects]]
from = "/protocols/*"
status = 404
to = "/protocols/404.html"
